- name: Install OpenSSH for Debian
  package:
    name: openssh-server
  become: true
  when: ansible_os_family == 'Debian'

- name: Install OpenSSH for Arch
  package:
    name: openssh
  become: true
  when: ansible_os_family == 'ArchLinux'

- name: Define context
  set_fact:
    user: jake
    enable_root: false

- name: SSH config
  template:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -t -f %s
    backup: yes
  become: true
  register: sshd_config

- name: Set up authorized keys
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ item }}"
  with_file:
    - ssh-keys/ps.pub

- name: Enable SSH
  service:
    name: sshd
    enabled: true
  become: true

- name: Restart SSH Daemon
  service:
    name: sshd
    state: reloaded
  when: sshd_config.changed
  become: true
