version: "2.3"

services:
  contessa:
    image: minio/minio:latest
    restart: unless-stopped
    volumes:
      - /mnt/tank/contessa:/data
    command: server /data --quiet
    environment:
      - MINIO_ACCESS_KEY={{ minio_access_key }}
      - MINIO_SECRET_KEY={{ minio_secret_key }}
    labels:
      - traefik.enable=true
      - traefik.http.routers.contessa.rule=Host(`contessa.jakehoward.tech`)
      - traefik.http.routers.contessa.tls.certresolver=le
