version: "2.3"
services:
  calibre:
    image: linuxserver/calibre-web:latest
    container_name: calibre
    environment:
      - PUID={{ docker_user.id }}
      - PGID={{ docker_user.id }}
      - TZ=Europe/London
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /srv/nextcloud-data/data/jake/files/EBooks:/books:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.rule=Host(`calibre.jakehoward.tech`)"
      - "traefik.http.routers.calibre.tls.certresolver=le"
