version: "2.3"

services:
  heimdall:
    image: linuxserver/heimdall:latest
    environment:
      - PUID={{ docker_user.id }}
      - PGID={{ docker_user.id }}
      - TZ=Europe/London
    restart: unless-stopped
    volumes:
      - "{{ app_data_dir }}/heimdall/:/config"
    labels:
      - traefik.enable=true
      - traefik.http.routers.heimdall.rule=Host(`jakehoward.tech`)
      - traefik.http.routers.heimdall.tls.certresolver=le
      - traefik.http.services.heimdall-heimdall.loadbalancer.server.port=443
      - traefik.http.services.heimdall-heimdall.loadbalancer.server.scheme=https
