version: "2.3"
services:
  duplicati:
    image: linuxserver/duplicati:v2.0.5.1-2.0.5.1_beta_2020-01-18-ls60
    container_name: duplicati
    environment:
      - PUID={{ docker_user.id }}
      - PGID={{ docker_user.id }}
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - ./restore:/restore
      - /:/source:ro
    restart: unless-stopped
    ports:
      - 8200:8200
