version: "2.3"
services:
  duplicati:
    image: linuxserver/duplicati:v2.0.5.1-2.0.5.1_beta_2020-01-18-ls61
    hostname: "{{ ansible_fqdn }}"
    environment:
      - PUID={{ docker_user.id }}
      - PGID={{ docker_user.id }}
      - TZ=Europe/London
    volumes:
      - ./config:/config
      - ./restore:/restore
      - /:/source:ro
    restart: unless-stopped
    ports:
      - "{{ wireguard.clients[ansible_fqdn].ip }}:8200:8200"
