version: "2.3"

services:
  wallabag:
    image: wallabag/wallabag:2.4.0
    restart: unless-stopped
    environment:
      - SYMFONY__ENV__SECRET={{ wallabag_secret }}
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.jakehoward.tech
    volumes:
      - "{{ app_data_dir }}/wallabag/data:/var/www/wallabag/data"
      - "{{ app_data_dir }}/wallabag/images:/var/www/wallabag/images"
    labels:
      - traefik.enable=true
      - traefik.http.routers.wallabag.rule=Host(`wallabag.jakehoward.tech`)
      - traefik.http.routers.wallabag.tls.certresolver=le
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - /mnt/tank/dbs/redis/wallabag:/data
