version: "2.3"

services:
  whoami:
    image: traefik/whoami:latest
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.theorangeone.net`) || Host(`who.0rng.one`)
      - traefik.http.routers.whoami.tls.certresolver=le
