version: "2.3"

services:
  deluge:
    image: linuxserver/deluge:latest
    environment:
      - PUID={{ docker_user.id }}
      - PGID={{ docker_user.id }}
      - TZ=Europe/London
    volumes:
      - "{{ app_data_dir }}/deluge:/config"
      - /mnt/tank/downloads:/downloads
    ports:
      - "{{ wireguard.clients[ansible_fqdn].ip }}:8112:8112"
    restart: unless-stopped
    depends_on:
      - tor-socks-proxy

  tor-socks-proxy:
    image: peterdavehello/tor-socks-proxy:latest
    restart: unless-stopped

  egress:
    image: theorangeone/static-server:latest
    restart: unless-stopped
    environment:
      - INDEX=on
    volumes:
      - /mnt/tank/downloads:/srv:ro
    ports:
      - "{{ wireguard.clients[ansible_fqdn].ip }}:8180:80"
