version: "2.3"
services:
  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ home }}/.docker/config.json:/config.json:ro"
    command: --cleanup --interval 600
    restart: unless-stopped
