version: "2.3"

services:
  wallabag:
    image: wallabag/wallabag:latest
    container_name: wallabag
    restart: unless-stopped
    environment:
      - SYMFONY__ENV__SECRET={{ wallabag_secret }}
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.jakehoward.tech
    volumes:
      - ./data:/var/www/wallabag/data
      - ./images:/var/www/wallabag/images
    labels:
      - traefik.enable=true
      - traefik.http.routers.wallabag.rule=Host(`wallabag.jakehoward.tech`)
      - traefik.http.routers.wallabag.tls.certresolver=le
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    volumes:
      - ./redis:/data
