version: "2.3"

services:
  web:
    image: linuxserver/scrutiny:latest
    ports:
      - "{{ wireguard.clients[ansible_fqdn].ip }}:7278:8080"
    volumes:
      - "{{ app_data_dir }}/scrutiny/:/config"
    environment:
      - SCRUTINY_WEB=true
      - PUID={{ docker_user.id }}
      - PGID={{ docker_user.id }}
    restart: unless-stopped

  collector:
    image: linuxserver/scrutiny:latest
    privileged: true
    volumes:
      - /dev/disk:/dev/disk
      - /run/udev:/run/udev:ro
      - "{{ app_data_dir }}/scrutiny/:/config"
    environment:
      - SCRUTINY_COLLECTOR=true
      - SCRUTINY_API_ENDPOINT=http://web:8080
      - PUID={{ docker_user.id }}
      - PGID={{ docker_user.id }}
    restart: unless-stopped
