# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  auth_mfa_modules:
    - type: totp

influxdb:
  host: host.docker.internal
  port: 48086

person:
  - name: Jake
    id: 0f9914e2a9c547adac98db4501b3067b
    device_trackers:
      - device_tracker.gm1913
