# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  auth_mfa_modules:
    - type: totp

influxdb:
  host: 127.0.0.1
  port: 48086

tado:
  username: !secret tado_username
  password: !secret tado_password

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

light:
  - platform: flux_led
    automatic_add: true
