# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  auth_mfa_modules:
    - type: totp

influxdb:
  host: 127.0.0.1
  port: 48086

light:
  - platform: flux_led
    automatic_add: true

recorder:
  db_url: postgres://home-assistant:home-assistant@127.0.0.1:45432/home-assistant
