version: "2.3"

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    network_mode: host
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/London
    restart: unless-stopped
    depends_on:
      - influxdb
    extra_hosts:
      - host.docker.internal:172.17.0.1
    labels:
      - traefik.enable=true
      - traefik.http.routers.homeassistant.rule=Host(`homeassistant.jakehoward.tech`)
      - traefik.http.routers.homeassistant.tls.certresolver=le
      - traefik.http.services.home-assistant-homeassistant.loadbalancer.server.port=8123

  influxdb:
    image: influxdb:1.8-alpine
    restart: unless-stopped
    volumes:
      - ./influxdb:/var/lib/influxdb
    ports:
      - 127.0.0.1:48086:8086
    environment:
      - INFLUXDB_DB=home_assistant
      - INFLUXDB_HTTP_AUTH_ENABLED=

  esphome:
    image: esphome/esphome:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./esphome:/config
