version: "2.3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:v5.0
    ports:
      - "{{ wireguard.clients.intersect.ip }}:53:53/tcp"
      - "{{ wireguard.clients.intersect.ip }}:53:53/udp"
    environment:
      - TZ=Europe/London
      - VIRTUAL_HOST=pihole.jakehoward.tech
    volumes:
      - ./pihole/:/etc/pihole/
      - ./dnsmasq.d/:/etc/dnsmasq.d/
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.jakehoward.tech`)"
      - "traefik.http.routers.pihole.tls.certresolver=le"
      - "traefik.http.routers.pihole.middlewares=internal-only@file"
      - "traefik.http.services.pihole-pihole.loadbalancer.server.port=80"
