version: "2.3"
services:
  duplicati:
    image: gotify/server:2.0.18
    environment:
      - TZ=Europe/London
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.gotify.rule=Host(`gotify.jakehoward.tech`)
      - traefik.http.routers.gotify.tls.certresolver=le
