- name: Create install directory
  file:
    path: /opt/gitlab-pages
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/gitlab-pages/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: /usr/bin/docker-compose -f %s config
  notify: restart gitlab-pages
  become: true

- name: Install rsync installer
  template:
    src: files/install-rsync.sh
    dest: /opt/gitlab-pages/install-rsync.sh
    mode: 0755
    owner: "998"
  notify: restart gitlab-pages
  become: true
