- name: Include gitea variables
  include_vars: gitea.yml

- name: Create gitea directory
  file:
    path: /opt/gitea
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Create gitea config directory
  file:
    path: /opt/gitea/gitea/gitea/conf
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install gitea compose file
  template:
    src: files/gitea/docker-compose.yml
    dest: /opt/gitea/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: /usr/bin/docker-compose -f %s config
  register: compose_file
  become: true

- name: Install gitea config file
  template:
    src: files/gitea/app.ini
    dest: /opt/gitea/gitea/gitea/conf/app.ini
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  register: gitea_config_file
  become: true

- name: Install git-mirror config file
  template:
    src: files/gitea/git-mirror-repositories.toml
    dest: /opt/gitea/repositories.toml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  register: git_mirror_config_file
  become: true

- name: restart gitea
  shell:
    chdir: /opt/gitea
    cmd: "{{ docker_update_command }}"
  when: compose_file.changed or gitea_config_file.changed or git_mirror_config_file.changed
