- name: Include librespeed variables
  include_vars: librespeed.yml

- name: Create librespeed directory
  file:
    path: /opt/librespeed
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install librespeed compose file
  template:
    src: files/librespeed/docker-compose.yml
    dest: /opt/librespeed/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: /usr/bin/docker-compose -f %s config
  register: compose_file
  become: true

- name: Cycle librespeed container
  docker_compose:
    project_src: /opt/librespeed
    pull: true
    remove_orphans: true
    remove_volumes: true
    state: "{{ item }}"
  when: compose_file.changed
  loop:
    - absent
    - present
