- name: Create tt-rss directory
  file:
    path: /opt/tt-rss
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install tt-rss compose file
  template:
    src: files/tt-rss/docker-compose.yml
    dest: /opt/tt-rss/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: /usr/bin/docker-compose -f %s config
  register: compose_file
  become: true

- name: Create tt-rss config directory
  file:
    path: /opt/tt-rss/config
    state: directory
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install tt-rss config
  template:
    src: files/tt-rss/config.php
    dest: /opt/tt-rss/config/config.php
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
  register: config_file
  become: true

- name: restart tt-rss
  shell:
    chdir: /opt/tt-rss
    cmd: "{{ docker_update_command }}"
  when: compose_file.changed or config_file.changed
