- name: Create whoami directory
  file:
    path: /opt/whoami
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install whoami compose file
  template:
    src: files/whoami/docker-compose.yml
    dest: /opt/whoami/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: /usr/bin/docker-compose -f %s config
  register: compose_file
  become: true

- name: Cycle whoami container
  docker_compose:
    project_src: /opt/whoami
    pull: true
    remove_orphans: true
    remove_volumes: true
    state: "{{ item }}"
  when: compose_file.changed
  loop:
    - absent
    - present
