version: "2.3"

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - TZ=Europe/London
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    restart: unless-stopped
    networks:
      - default
      - grafana

networks:
  grafana:
    external: true
