- name: Enable zfs module
  modprobe:
    name: zfs
    state: present
    params: zfs_arc_max={{ zfs_arc_size }}

- name: ZFS Scrub
  cron:
    name: zfs scrub {{ item }}
    special_time: weekly
    job: zpool scrub {{ item }}
  become: true
  loop: "{{ zpools_to_scrub }}"

- name: Sanoid
  include: sanoid.yml
