- name: Enable zfs module
  modprobe:
    name: zfs
    state: present
    params: zfs_arc_max={{ zfs_arc_size }}

- name: ZFS Scrub
  cron:
    name: zfs scrub
    special_time: weekly
    job: zpool scrub tank
  become: true

- name: Sanoid
  include: sanoid.yml
