http:
  middlewares:
    internal-only:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"

  routers:
    hsts:
      service: ping@internal
      rule: PathPrefix(`/`)
      entryPoints:
        - web
    ping:
      service: ping@internal
      rule: Host(`traefik.jakehoward.tech`) && Path(`/ping/`)
      tls:
        certResolver: le
    dashboard:
      service: dashboard@internal
      rule: Host(`traefik.jakehoward.tech`)
      middlewares:
        - internal-only
      tls:
        certResolver: le
    api:
      service: api@internal
      rule: Host(`traefik.jakehoward.tech`) && PathPrefix(`/api`)
      middlewares:
        - internal-only
      tls:
        certResolver: le
