version: "2.3"
services:
  deluge:
    image: linuxserver/deluge:latest
    environment:
      - PUID={{ docker_user.id }}
      - PGID={{ docker_user.id }}
      - TZ=Europe/London
    volumes:
      - /mnt/tank/app-data/deluge:/config
      - /scratch/deluge:/downloads
    ports:
      - 8112:8112
    restart: unless-stopped
    depends_on:
      - tor-socks-proxy

  tor-socks-proxy:
    image: peterdavehello/tor-socks-proxy:latest
    restart: unless-stopped
