version: "2.3"

services:
  folding-at-home:
    image: linuxserver/foldingathome:latest
    cpus: 0.75
    environment:
      - TZ=Europe/London
      - PUID={{ docker_user.id }}
      - GUID={{ docker_user.id }}
    volumes:
      - ./config:/config
    ports:
      - 7396:7396
    restart: unless-stopped
