- name: Include docker variables
  include_vars: docker.yml

- name: Install Docker
  include: setup-docker.yml

# Applications

- name: Install calibre
  include: calibre.yml

- name: Install duplicati
  include: duplicati.yml

- name: Install emby
  include: emby.yml

- name: Install folding-at-home
  include: folding-at-home.yml

- name: Install gitea
  include: gitea.yml

- name: Install gotify
  include: gotify.yml

- name: Install librespeed
  include: librespeed.yml

- name: Install netdata
  include: netdata.yml

- name: Install nextcloud
  include: nextcloud.yml

- name: Install pihole
  include: pihole.yml

- name: Install quassel
  include: quassel.yml

- name: Install statping
  include: statping.yml

- name: Install synapse
  include: synapse.yml

- name: Install todoist-github
  include: todoist-github.yml

- name: Install torrent
  include: torrent.yml

- name: Install theorangeone.net
  include: theorangeone.net.yml

- name: Install traefik
  include: traefik.yml

- name: Install tt-rss
  include: tt-rss.yml

- name: Install wallabag
  include: wallabag.yml

- name: Install watchtower
  include: watchtower.yml

- name: Install whoami
  include: whoami.yml

- name: Install yourls
  include: yourls.yml
