- name: Include docker variables
  include_vars: docker.yml

- name: Install Docker
  include: setup-docker.yml

- name: Install netdata
  include: netdata.yml

- name: Install watchtower
  include: watchtower.yml

- name: Install portainer
  include: portainer.yml

- name: Install dnsmasq
  include: dnsmasq.yml

- name: Install whoami
  include: whoami.yml

- name: Install emby
  include: emby.yml

- name: Install librespeed
  include: librespeed.yml

- name: Install gotify
  include: gotify.yml

- name: Install traefik
  include: traefik.yml

- name: Install calibre
  include: calibre.yml

- name: Install gitea
  include: gitea.yml

- name: Install yourls
  include: yourls.yml

- name: Install tt-rss
  include: tt-rss.yml

- name: Install torrent
  include: torrent.yml

- name: Install quassel
  include: quassel.yml

- name: Install synapse
  include: synapse.yml

- name: Install nextcloud
  include: nextcloud.yml

- name: Install todoist-github
  include: todoist-github.yml
