- hosts: all
  roles:
    - base
    - role: geerlingguy.ntp
      become: true
      vars:
        ntp_timezone: Europe/London
        ntp_manage_config: true
    - role: realorangeone.reflector
      when: ansible_os_family == 'Archlinux'

- hosts: casey
  roles:
    - gateway

- hosts:
    - intersect
    - walker
    - grimes
    - pve-docker
  roles:
    - role: geerlingguy.docker
      become: true
      vars:
        docker_install_compose: false  # This role installs the binary directly, which is kinda nasty
        docker_package: "{{ 'docker-ce' if ansible_os_family == 'Debian' else 'docker' }}"
        docker_users:
          - "{{ user }}"
    - docker_cleanup
    - traefik

# ZFS Hosts
- hosts:
    - walker
    - intersect
  roles:
    - zfs

- hosts:
    - grimes
  roles:
    - plausible
    - duplicati

- hosts: intersect
  roles:
    - home_assistant
    - intersect_docker
    - duplicati
    - grafana
    - gitlab
    - scrutiny
    - heimdall

- hosts: walker
  roles:
    - contessa
    - upload
    - duplicati
    - gitlab_pages
    - deluge

- hosts: ingress
  roles:
    - ingress
