- hosts: all
  roles:
    - common
    - role: geerlingguy.ntp
      become: true
      vars:
        ntp_timezone: Europe/London
    - ssh

- hosts: casey
  roles:
    - gateway

- hosts: intersect
  roles:
    - role: geerlingguy.docker
      become: true
      vars:
        docker_install_compose: false  # This role installs the binary directly, which is kinda nasty
        docker_users:
          - "{{ user }}"
    - docker-cleanup
    - netdata
    - traefik
    - watchtower
    - docker
