- hosts: all
  roles:
    - base
    - role: geerlingguy.ntp
      become: true
      vars:
        ntp_timezone: Europe/London
    - role: realorangeone.reflector
      when: ansible_os_family == 'Archlinux'

- hosts: casey
  roles:
    - gateway

- hosts:
    - intersect
    - grimes
    - walker
  roles:
    - role: geerlingguy.docker
      become: true
      vars:
        docker_install_compose: false  # This role installs the binary directly, which is kinda nasty
        docker_package: "{{ 'docker-ce' if ansible_os_family == 'Debian' else 'docker' }}"
        docker_users:
          - "{{ user }}"
    - docker-cleanup
    - watchtower
    - traefik

# ZFS Hosts
- hosts:
    - walker
    - intersect
  roles:
    - zfs

- hosts: intersect
  roles:
    - netdata
    - home-assistant
    - intersect-docker
    - plausible
    - duplicati
    - grafana
    - gitlab

- hosts: walker
  roles:
    - contessa
    - statping
    - upload
    - website
    - duplicati
    - gitlab-pages
