- hosts: all
  roles:
    - base
    - role: geerlingguy.ntp
      become: true
      vars:
        ntp_timezone: Europe/London

- hosts: casey
  roles:
    - ssh
    - gateway

- hosts: intersect
  roles:
    - ssh
    - role: geerlingguy.docker
      become: true
      vars:
        docker_install_compose: false  # This role installs the binary directly, which is kinda nasty
        docker_users:
          - "{{ user }}"
    - docker
