- hosts: all
  roles:
    - base
    - role: geerlingguy.ntp
      become: true
      vars:
        ntp_timezone: Europe/London

- hosts: casey
  roles:
    - gateway

- hosts:
    - intersect
    - grimes
    - walker
  roles:
    - role: geerlingguy.docker
      become: true
      vars:
        docker_install_compose: false  # This role installs the binary directly, which is kinda nasty
        docker_package: "{{ 'docker-ce' if ansible_os_family == 'Debian' else 'docker' }}"
        docker_users:
          - "{{ user }}"
    - docker-cleanup
    - watchtower
    - traefik

- hosts: intersect
  roles:
    - netdata
    - home-assistant
    - intersect-docker
    - plausible
    - duplicati

- hosts: grimes
  roles:
    - socks-proxy

# Arch boxes
- hosts:
    - grimes
    - casey
    - walker
  roles:
    - realorangeone.reflector

- hosts: walker
  roles:
    - contessa
    - statping
    - upload
    - website
    - zfs
    - duplicati
