version: "2.3"

services:
  traefik:
    image: traefik:v2.2.4
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
    restart: unless-stopped
