http:
  middlewares:
    internal-only:
      ipWhiteList:
        sourceRange:
          - "10.0.0.0/8"
          - "172.16.0.0/12"
          - "192.168.0.0/16"
    hsts:
      redirectScheme:
        scheme: https

  routers:
    hsts:
      service: ping@internal
      rule: PathPrefix(`/`)
      entryPoints:
        - web
      middlewares:
        - hsts
    ping:
      service: ping@internal
      rule: Host(`traefik.jakehoward.tech`) && Path(`/ping/`)
      middlewares:
        - hsts
      tls:
        certResolver: le
    dashboard:
      service: dashboard@internal
      rule: Host(`traefik.jakehoward.tech`)
      middlewares:
        - hsts
        - internal-only
      tls:
        certResolver: le
    api:
      service: api@internal
      rule: Host(`traefik.jakehoward.tech`) && PathPrefix(`/api`)
      middlewares:
        - hsts
        - internal-only
      tls:
        certResolver: le
