http:
  middlewares:
    tls-redirect:
      redirectScheme:
        scheme: https
    compress:
      compress: {}

  routers:
    tls-redirect:
      service: ping@internal
      rule: PathPrefix(`/`)
      entryPoints:
        - web
      middlewares:
        - tls-redirect
