http:
  routers:
    router-homeassistant:
      rule: Host(`homeassistant.jakehoward.tech`)
      service: service-homeassistant
      tls:
        certResolver: le
  services:
    service-homeassistant:
      loadBalancer:
        servers:
          - url: http://192.168.2.41:8123
