http:
  middlewares:
    internal-only:
      ipWhiteList:
        sourceRange:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
    tls-redirect:
      redirectScheme:
        scheme: https

  routers:
    tls-redirect:
      service: ping@internal
      rule: PathPrefix(`/`)
      entryPoints:
        - web
      middlewares:
        - tls-redirect
