entryPoints:
  web:
    address: :80
    proxyProtocol:
      trustedIPs:
        - "{{ traefik_proxy_protocol_trusted_ips }}"
  web-secure:
    address: :443
    proxyProtocol:
      trustedIPs:
        - "{{ traefik_proxy_protocol_trusted_ips }}"
  matrix:
    address: :8448
    proxyProtocol:
      trustedIPs:
        - "{{ traefik_proxy_protocol_trusted_ips }}"
  traefik:
    address: "{{ traefik_private_ip }}:8080"

ping: {}

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    watch: true
    exposedByDefault: false
  file:
    directory: /etc/traefik/conf

api:
  dashboard: true
  insecure: true

certificatesResolvers:
  le:
    acme:
      email: hosting@theorangeone.net
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53

serversTransport:
  insecureSkipVerify: true

metrics:
  influxDB:
    address: "{{ traefik_private_ip }}:38089"
    database: traefik
    pushInterval: 30s

tls:
  options:
    default:
      minVersion: VersionTLS12
