- name: Create install directory
  file:
    path: /opt/gitlab
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: true

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/gitlab/docker-compose.yml
    mode: "{{ docker_compose_file_mask }}"
    owner: "{{ docker_user.name }}"
    validate: /usr/bin/docker-compose -f %s config
  notify: restart gitlab
  become: true

- name: Install lsyncd config
  template:
    src: files/lsyncd.lua
    dest: /mnt/tank/app-data/gitlab/lsyncd/lsyncd.lua
    mode: "{{ docker_compose_file_mask }}"
    owner: "998"
  notify: restart gitlab
  become: true
