name: CI

on: [push]

jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: pip-${{ hashFiles('ansible/requirements.txt') }}-${{ hashFiles('ansible/dev-requirements.txt') }}
      - name: Install dependencies
        run: ./scripts/ansible/setup.sh
      - name: Run linters
        run: ./scripts/ansible/lint.sh

  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "0.13.0"
      - name: Initialize Terraform
        run: ./scripts/terraform/terraform.sh init -backend=false
      - name: Lint
        run: ./scripts/terraform/lint.sh
